numpy's most useful feature is n diementional array object also known as 
ndarray

In [1]:
import numpy as np

In [8]:
a = np.array([1,2,3]) #create an array object

In [15]:
a 
# a[2] #quite similar to the List

array([1, 2, 3])

It is similiar to list but why we use numpy array over list?
beacuse 1. Less memory 2. Fast 3.Convenient

In [3]:
import time , sys

lists = range(1000)
print(sys.getsizeof(5)*len(lists))

array = np.arange(1000)
print(array.size*array.itemsize)


28000
8000


here python list takes 28000 bytes where numpy array takes only 8000 bytes.


In [9]:
size = 10000

list1 = range(size)
list2 = range(size)

np1 = np.arange(size)
np2 = np.arange(size)

start_list = time.time()
result_list = [(x,y) for x,y in zip(list1,list2)]
print((time.time()-start_list)*1000)

start_np = time.time()
result_np = np1+np2

print((time.time()-start_np)*1000)



1.9989013671875
0.13637542724609375


here numpy array take much less time than list of python

In [34]:
#basic operations 
a1 = np.array([5,6,7])
a2 = np.array([[1,2],[3,4],[5,6]])
a3 = np.array([[1,2],[3,4],[5,6]], dtype = np.float64) #use to change datatype
print(a1.ndim) #ndim use to show how dimensions array it is
print(a2.ndim)
a1.itemsize

1
2


8

In [35]:
print(a1.dtype) #use to show datatype of array
print(a3.dtype)
print(a1.itemsize) #use to show size of each element
print(a3.itemsize)

int64
float64
8
8


In [42]:
print(a1.size) #shows the number of elements in the array
print(a2.size)
print(a1.shape) #represent the information on dimensions
print(a2.shape) #width and height or row and column

3
6
(3,)
(3, 2)


In [59]:
#initialize array with some placeholder number
z0 = np.zeros((3,4)) # array with all 0, zeros((rows,columns)) 
print (z0)

z1 = np.ones((3,4)) #array with all 1, ones(shape)
print(z1)

r1 = np.arange(1,5) # array range similiar as range in python
print(r1)
r2 = np.arange(1,5,2) # range(start,end+1,step)
print(r2)

l1 = np.linspace(1,5,10) # (start,end,linearly spaced number) 
print(l1)
l2 = np.linspace(1,5,5)
print(l2)

rs1 = np.array([[1,2],[3,4],[5,6]])
print(rs1.shape)
rs2 = rs1.reshape(2,3) #reshape rows and columns
print(rs2)
rs3 = rs1.reshape(6,1)
print(rs3)
rs4 = rs1.ravel() #ravel() makes array in one dimension
print(rs4)
#all these returns you a new array so if you need to keep this array 
#you can keep it to a new variable

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1 2 3 4]
[1 3]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1. 2. 3. 4. 5.]
(3, 2)
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]


In [77]:
#mathmetical functions
a1 = np.array([5,6,7])
a2 = np.array([[1,2],[3,4],[5,6]])
print("min : " ,a1.min())
print("max : ",a1.max())
print("sum a1: ",a1.sum())

print("sum a2: ",a2.sum())
print("sum of columns: ",a2.sum(axis = 0)) #axis 0 add colums wise
print("sum of rows: ",a2.sum(axis = 1)) # axis 1 add row wise

print("square roots : ",np.sqrt(a1))
print("standard deviation: ",np.std(a1))

min :  5
max :  7
sum a1:  18
sum a2:  21
sum of columns:  [ 9 12]
sum of rows:  [ 3  7 11]
square roots :  [2.23606798 2.44948974 2.64575131]
standard deviation:  0.816496580927726


In [87]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = a+b
d = a*b
e = a/b
f = a-b
g = a.dot(b)
print("additon : ")
print("multiplication : ",d)
print("division : ",e)
print("subtraction : ",f)
print("dot : ",g)

additon : 
multiplication :  [[ 5 12]
 [21 32]]
division :  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
subtraction :  [[-4 -4]
 [-4 -4]]
dot :  [[19 22]
 [43 50]]


In [9]:
#slicing/stacking and indexing
#indexing...........
i = np.array([3,4,5,6,7,8]) #for single array

print(i[0:7])
print(i[1:7:2])
print(i[2:])
print(i[:5])
print(i[-1])
print(i[-3:])
print(i[:-2])

[3 4 5 6 7 8]
[4 6 8]
[5 6 7 8]
[3 4 5 6 7]
8
[6 7 8]
[3 4 5 6]


In [16]:
i2 = np.array([[3,4,5],[1,2,3],[6,7,8]]) #multi dimensional array

print(i2[1,2]) #i2[row,column]
print(i2[0:2,2])
print(i2[-1]) #i2[-1] it indicates last row
print(i2[-1,0:2])
print(i2[:,:])

3
[5 3]
[6 7 8]
[6 7]
[[3 4 5]
 [1 2 3]
 [6 7 8]]


In [49]:
i2 = np.array([[3,4,5],[1,2,3],[6,7,8]]) #iteration

for row in i2:
    print(row) #print all rows
for values in i2.flat:
    print(values) #flattening all values
    
#assign to slice
sa1 = np.arange(10,121,10).reshape(3,4)
sa1[1,1:3] = 0 #assigning 0 t0 60 and 70
sa1

[3 4 5]
[1 2 3]
[6 7 8]
3
4
5
1
2
3
6
7
8


array([[ 10,  20,  30,  40],
       [ 50,   0,   0,  80],
       [ 90, 100, 110, 120]])

In [28]:
s1 = np.arange(6).reshape(3,2)
s2 = np.arange(6,12).reshape(3,2)
print(s1)
print(s2)

s3 = np.vstack((s1,s2)) #vertical stacking
print(s3)
s4 = np.hstack((s1,s2)) #horizontal stacking
print(s4)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [37]:
sp = np.arange(30).reshape(2,15)

hsp = np.hsplit(sp,3) #horizontal split
print(hsp)
print(hsp[0])

vsp = np.vsplit(sp,2) #vertically split
print(vsp)
print(vsp[1])

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [42]:
#boolean array

ar1 = np.arange(12).reshape(3,4)
ar2 = ar1 > 4
print(ar2) #shows boolean 
print(ar1[ar2]) #it returns those elements which is greater than 4
ar1[ar2] = -2 #assign -2 in all elements which is greater than 4
ar1

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4, -2, -2, -2],
       [-2, -2, -2, -2]])